<?xml version="1.0" encoding="utf-8"?><Database Name="TestAdo" Class="DataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TECH-LP-892;Initial Catalog=TestAdo;User ID=sa" SettingsObjectName="LINQtoSQL.Properties.Settings" SettingsPropertyName="TestAdoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>